version: '3.8'

services:
  gateway:
    build: ./Gateway_container
    ports:
      - "8000:8000"
    networks:
      - backend

  api:
    build: ./API_container
    env_file:
      - ./.env
    ports:
      - "8001:8001"
    networks:
      - backend

  llm:
    build: ./LLM_container
    env_file:
      - ./.env
    ports:
      - "8002:8002"
    networks:
      - backend


networks:
  backend:
    driver: bridge
    ipam:
      driver: default
